"""Add body column to messages table

Revision ID: c77a5734be8e
Revises: 3a34fa9d3a23
Create Date: 2024-01-14 08:58:55.783454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c77a5734be8e'
down_revision = '3a34fa9d3a23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages') as batch_op:
        batch_op.alter_column('created_at', type_=sa.DateTime)

    # ### end Alembic commands ###


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
